dockerRegistry: ghcr.io
imagePullSecrets: regkey
applicationName: api-backend
namespace: trace-prod
replicaCount: 2
image:
  name: vektor-code/api-backend
  tag: prod-cd4501c
  pullPolicy: Always
secrets:
  enabled: false
  data: []
configmaps:
  enabled: false
terminationGracePeriodSeconds: 30
ports:
  enabled: true
  containerPort: 8080
service:
  enabled: true
  type: LoadBalancer
  port: 8080
hostsfile:
  enabled: false
  records: []
strategy:
  enabled: true
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
minReadySeconds: 5
revisionHistoryLimit: 3
hpa:
  enabled: true
  minReplicas: "2"
  maxReplicas: "10"
  cpuUtilization: "80"
  memoryUtilization: "75"
resources:
  enabled: true
  limits:
    memory: 2Gi
    cpu: "2"
  requests:
    cpu: 500m
    memory: 1Gi
readinessProbe:
  enabled: true
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 5
  successThreshold: 1
istio:
  enabled: false
ingress:
  enabled: true
  hostname: api-trace.rdmis.gov.az
  tls: true
  tlsSecretName: api-backend
  routes:
    - route: /
      service: api-backend
      namespace: trace-prod
      port: 8080
  annotations:
    kubernetes.io/ingress.class: nginx
instrumentation:
  enabled: false
  exporterEndpoint: ""
env:
  - name: MINIO_ENDPOINT
    value: "10.254.6.25:9000"
  - name: MINIO_USE_SSL
    value: "false"
  - name: MINIO_ACCESS_KEY
    value: "trace"
  - name: MINIO_SECRET_KEY
    value: "slmM4lCsMGFMSqBB"
  - name: MINIO_BUCKET
    value: "trace"
  - name: KUBETRACE_DEMO
    value: "false"
  - name: TZ
    value: UTC
  - name: JWT_SECRET
    value: "super-secret-key-2026"
  - name: ADMIN_USERNAME
    value: "admin"
  - name: ADMIN_PASSWORD
    value: "tracesvc-admin-pass-2026"
  - name: LDAP_ENABLED
    value: "true"
  - name: LDAP_URL
    value: "ldap://10.254.5.10:389"
  - name: LDAP_BIND_DN
    value: "CN=tracesvc,OU=SERVICE_USERS,OU=MOF,DC=mof,DC=local"
  - name: LDAP_BIND_PASSWORD
    value: "jOg13snoLbqYEecq"
  - name: LDAP_USER_BASE_DN
    value: "OU=MOF,DC=mof,DC=local"
  - name: LDAP_USER_FILTER
    value: "(&(objectClass=user)(sAMAccountName={login})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
  - name: LDAP_USER_NAME_ATTR
    value: "displayName"
  - name: LDAP_USER_EMAIL_ATTR
    value: "mail"
hostpathVolume:
  enabled: false
volumeMounts:
  enabled: false
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
