apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.applicationName }}-watcher
  labels:
    app.kubernetes.io/name: {{ .Values.applicationName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.applicationName }}-watcher
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
